# Generated by Django 6.1 on 2026-08-26 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectmembership',
            name='unique_project_membership',
        ),
        migrations.RenameField(
            model_name='projectmembership',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_membership'),
        ),
    ]
