from rest_framework.permissions import BasePermission, SAFE_METHODS
from users.models import User
from users.permissions import HasRole

class TestSuiteObjectPermission(BasePermission):
    """
    Object level permissions TestSuite.

    Rules:
    - Authenticated users can view suites
    - ADMIN can create an modify suite
    - QA ENGINEER can create suites and modify suites they created
    - DEVELOPER cannot create or modify suites
    - VIEWER cannot create or modify suites
    """
    def has_permission(self, request, view):
        if not request.user.is_authenticated:
            return False

        # Everyone authenticated can read
        if request.method in SAFE_METHODS:
            return True

        # Only ADMIN and QA_ENGINEER can create/modify suites
        return request.user.role in [
            User.Role.ADMIN,
            User.Role.QA_ENGINEER,
        ]
    
    def has_object_permission(self, request, view, obj):
        # Anyone Authenticated can view
        if request.method in SAFE_METHODS:
            return True

        # Anyone can modify any suite
        if request.user.role == User.role.ADMIN:
            return True

        # QA Engineer can modify suites they created
        return (
            request.user.role == User.Role.QA_ENGINEER
            and obj.created_by == request.user
        )

class TestCasePermission(BasePermission):
    """
    Object-level permissions for TestCase.

    Rules:
    - Authenticated users can view test cases.
    - ADMIN can create and modify any test case.
    - QA_ENGINEER can create test cases and modify their own.
    - DEVELOPER cannot create or modify test cases.
    - VIEWER cannot create or modify test cases.
    """
    def has_permission(self, request, view):
        if not request.user.is_authenticated:
            return False

        # Everyone authenticated can read
        if request.method in SAFE_METHODS:
            return True

        # Only ADMIN and QA_ENGINEER can create/modify test cases
        return request.user.role in [
            User.Role.ADMIN,
            User.Role.QA_ENGINEER,
        ]
    
    def has_object_permission(self, request, view, obj):
        # Everyone authenticated can view
        if request.method in SAFE_METHODS:
            return True

        # ADMIN can modify any test case
        if request.user.role == User.Role.ADMIN:
            return True

        # QA_ENGINEER can modify their own test cases
        return (
            request.user.role == User.Role.QA_ENGINEER
            and obj.created_by == request.user
        )

class TestRunPermission(BasePermission):
    """
    Object-level permissions for TestRun.

    Rules:
    - Authenticated users can view test runs.
    - ADMIN can create and modify any test run.
    - QA_ENGINEER can create test runs and modify their own.
    - DEVELOPER can create test runs.
    - DEVELOPER cannot modify an existing test run.
    - VIEWER cannot create or modify test runs.
    """
    def has_permission(self, request, view):
        if not request.user.is_authenticated:
            return False

        # Anyone Authenticated can read
        if request.method in SAFE_METHODS:
            return True

        # ADMIN, QA_ENGINEER and DEVELOPER
        # can create TestRuns
        return request.user.role in [
            User.Role.ADMIN,
            User.Role.QA_ENGINEER,
            User.Role.DEVELOPER,
        ]
    
    def has_object_permission(self, request, view, obj):
        # Everyone authenticated can view
        if request.method in SAFE_METHODS:
            return True

        # Admin
        if request.user.role == User.Role.ADMIN:
            return True

        # QA can modify their own TestRuns
        if (
            request.user.role == User.Role.QA_ENGINEER
            and obj.created_by == request.user
        ):
            return True

        # Developer can modify their own TestRuns
        if (
            request.user.role == User.Role.DEVELOPER
            and obj.created_by == request.user
        ):
            return True

        # DEVELOPER can create Testruns,
        # but cannot modift existing Testruns.
        return False

class TestResultPermission(BasePermission):
    """
    TestResults are read-only through the API.

    TestResults should normally be generated by the
    test execution system rather than manually modified
    through the API.
    """

    def has_permission(self, request, view):
        if not request.user.is_authenticated:
            return False

        # Everyone authenticated can view results
        if request.method in SAFE_METHODS:
            return True

        # No direct POST/PUT/PATCH/DELETE through this API
        return False

class CanExecuteTests(HasRole):
    """
    Roles allowed to execute test cases.
    """
    allowed_roles = [
        User.Role.QA_ENGINEER,
        User.Role.ADMIN,
        User.Role.DEVELOPER,
    ]

class CanManageTestCases(HasRole):
    """
    Roles allowed to create/manage test cases.
    """
    allowed_roles = [
        User.Role.ADMIN,
        User.Role.QA_ENGINEER,
    ]

class CanManageTestSuite(HasRole):
    """
    Roles allowed to create/manage test suites.
    """
    allowed_roles = [
        User.Role.ADMIN,
        User.Role.QA_ENGINEER,
    ]