# Generated by Django 6.1 on 2026-08-20 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_tag_testcase_tags_tag_unique_tag_name_per_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_test_runs', to=settings.AUTH_USER_MODEL)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='testing.testsuite')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('BLOCKED', 'Blocked')], max_length=10)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='testing.testcase')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testing.testrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('test_run', 'test_case'), name='unique_test_result_per_run')],
            },
        ),
    ]
